# Generated by Django 5.2.7 on 2025-10-26 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('role_change', 'Role Change'), ('permission_grant', 'Permission Grant'), ('permission_revoke', 'Permission Revoke'), ('user_create', 'User Create'), ('user_update', 'User Update'), ('user_delete', 'User Delete'), ('user_activate', 'User Activate'), ('user_deactivate', 'User Deactivate'), ('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('2fa_enable', '2FA Enable'), ('2fa_disable', '2FA Disable'), ('account_lock', 'Account Lock'), ('account_unlock', 'Account Unlock')], max_length=50)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', 'timestamp'], name='auth_audit__actor_i_b1353e_idx'), models.Index(fields=['target_user', 'timestamp'], name='auth_audit__target__352dc3_idx'), models.Index(fields=['action', 'timestamp'], name='auth_audit__action_58b95b_idx')],
            },
        ),
    ]
