# Generated by Django 5.2.7 on 2025-10-26 23:54

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=500)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'start_date'], name='donations_d_status_379abc_idx'), models.Index(fields=['slug'], name='donations_d_slug_410bfc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_phone', models.CharField(blank=True, max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mtn_momo', 'MTN Mobile Money'), ('vodafone_cash', 'Vodafone Cash'), ('airteltigo_money', 'AirtelTigo Money'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('payment_processor_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('donation_type', models.CharField(choices=[('one_time', 'One-time'), ('monthly', 'Monthly Recurring'), ('quarterly', 'Quarterly Recurring'), ('yearly', 'Yearly Recurring')], default='one_time', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('refund_date', models.DateTimeField(blank=True, null=True)),
                ('donor_message', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('receipt_sent_at', models.DateTimeField(blank=True, null=True)),
                ('tax_deductible', models.BooleanField(default=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.donationcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('receipt_date', models.DateTimeField(auto_now_add=True)),
                ('tax_year', models.PositiveIntegerField()),
                ('tax_deductible_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='donations.donation')),
            ],
            options={
                'ordering': ['-receipt_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringDonation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mtn_momo', 'MTN Mobile Money'), ('vodafone_cash', 'Vodafone Cash'), ('airteltigo_money', 'AirtelTigo Money'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('subscription_id', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('next_payment_date', models.DateTimeField()),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('total_donations', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_donations', to='donations.donationcampaign')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', 'payment_date'], name='donations_d_status_76d81d_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor_email'], name='donations_d_donor_e_914ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['campaign', 'status'], name='donations_d_campaig_5c4298_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['payment_method', 'status'], name='donations_d_payment_985953_idx'),
        ),
        migrations.AddIndex(
            model_name='donationreceipt',
            index=models.Index(fields=['receipt_number'], name='donations_d_receipt_6917e9_idx'),
        ),
        migrations.AddIndex(
            model_name='donationreceipt',
            index=models.Index(fields=['tax_year'], name='donations_d_tax_yea_4cbb7a_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringdonation',
            index=models.Index(fields=['status', 'next_payment_date'], name='donations_r_status_f4dda3_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringdonation',
            index=models.Index(fields=['donor', 'status'], name='donations_r_donor_i_6af6dc_idx'),
        ),
    ]
