# Generated by Django 5.2.7 on 2025-10-27 00:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[('page_views', 'Page Views'), ('user_actions', 'User Actions'), ('content_performance', 'Content Performance'), ('donation_analytics', 'Donation Analytics'), ('volunteer_analytics', 'Volunteer Analytics'), ('system_metrics', 'System Metrics')], max_length=30, unique=True)),
                ('retention_days', models.PositiveIntegerField()),
                ('anonymization_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_cleanup', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['data_type'],
            },
        ),
        migrations.CreateModel(
            name='AnonymizedUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_id', models.CharField(max_length=64, unique=True)),
                ('age_range', models.CharField(blank=True, max_length=20)),
                ('location_region', models.CharField(blank=True, max_length=100)),
                ('user_type', models.CharField(blank=True, max_length=20)),
                ('first_visit', models.DateTimeField()),
                ('last_activity', models.DateTimeField()),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('is_active_user', models.BooleanField(default=False)),
                ('has_donated', models.BooleanField(default=False)),
                ('has_volunteered', models.BooleanField(default=False)),
                ('has_subscribed_newsletter', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['anonymous_id'], name='analytics_a_anonymo_49d6b2_idx'), models.Index(fields=['user_type', 'is_active_user'], name='analytics_a_user_ty_ad4b22_idx'), models.Index(fields=['last_activity'], name='analytics_a_last_ac_298894_idx')],
            },
        ),
        migrations.CreateModel(
            name='DonationAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_range', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=20)),
                ('donation_type', models.CharField(max_length=20)),
                ('donor_age_range', models.CharField(blank=True, max_length=20)),
                ('donor_location_region', models.CharField(blank=True, max_length=100)),
                ('is_repeat_donor', models.BooleanField(default=False)),
                ('campaign_category', models.CharField(blank=True, max_length=100)),
                ('donation_date', models.DateField()),
            ],
            options={
                'ordering': ['-donation_date'],
                'indexes': [models.Index(fields=['donation_date'], name='analytics_d_donatio_83d320_idx'), models.Index(fields=['amount_range', 'donation_date'], name='analytics_d_amount__8683ac_idx'), models.Index(fields=['payment_method', 'donation_date'], name='analytics_d_payment_9e9404_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('daily_active_users', 'Daily Active Users'), ('page_load_time', 'Page Load Time'), ('api_response_time', 'API Response Time'), ('error_rate', 'Error Rate'), ('conversion_rate', 'Conversion Rate'), ('bounce_rate', 'Bounce Rate'), ('session_duration', 'Session Duration')], max_length=30)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('metric_unit', models.CharField(blank=True, max_length=20)),
                ('page_url', models.URLField(blank=True)),
                ('user_segment', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('hour', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date', '-hour'],
                'indexes': [models.Index(fields=['metric_type', 'date'], name='analytics_s_metric__1f1ebf_idx'), models.Index(fields=['date', 'hour'], name='analytics_s_date_254571_idx'), models.Index(fields=['page_url', 'date'], name='analytics_s_page_ur_4fa17b_idx')],
            },
        ),
        migrations.CreateModel(
            name='VolunteerAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('volunteer_age_range', models.CharField(blank=True, max_length=20)),
                ('volunteer_location_region', models.CharField(blank=True, max_length=100)),
                ('application_status', models.CharField(max_length=20)),
                ('opportunity_category', models.CharField(blank=True, max_length=100)),
                ('commitment_type', models.CharField(blank=True, max_length=20)),
                ('skill_categories', models.JSONField(blank=True, default=list)),
                ('application_date', models.DateField()),
            ],
            options={
                'ordering': ['-application_date'],
                'indexes': [models.Index(fields=['application_date'], name='analytics_v_applica_b161f8_idx'), models.Index(fields=['application_status', 'application_date'], name='analytics_v_applica_cf6379_idx'), models.Index(fields=['volunteer_age_range'], name='analytics_v_volunte_806a14_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('average_time_on_page', models.FloatField(default=0.0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('total_downloads', models.PositiveIntegerField(default=0)),
                ('total_interactions', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('goal_completions', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'date'], name='analytics_c_content_2d773f_idx'), models.Index(fields=['date'], name='analytics_c_date_20795c_idx')],
                'unique_together': {('content_type', 'object_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_url', models.URLField()),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('referrer_url', models.URLField(blank=True)),
                ('session_id', models.CharField(max_length=64)),
                ('user_agent_category', models.CharField(blank=True, max_length=50)),
                ('browser_family', models.CharField(blank=True, max_length=50)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('time_on_page', models.PositiveIntegerField(blank=True, null=True)),
                ('anonymous_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.anonymizeduser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['anonymous_user', 'created_at'], name='analytics_p_anonymo_4bbe2a_idx'), models.Index(fields=['page_url', 'created_at'], name='analytics_p_page_ur_b854b8_idx'), models.Index(fields=['session_id'], name='analytics_p_session_a580f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('page_view', 'Page View'), ('button_click', 'Button Click'), ('form_submit', 'Form Submit'), ('download', 'Download'), ('donation', 'Donation'), ('volunteer_application', 'Volunteer Application'), ('newsletter_signup', 'Newsletter Signup'), ('search', 'Search'), ('share', 'Share'), ('contact_form', 'Contact Form')], max_length=30)),
                ('action_name', models.CharField(max_length=100)),
                ('page_url', models.URLField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(max_length=64)),
                ('anonymous_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='analytics.anonymizeduser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['anonymous_user', 'action_type'], name='analytics_u_anonymo_ab515c_idx'), models.Index(fields=['action_type', 'created_at'], name='analytics_u_action__1ca732_idx'), models.Index(fields=['session_id'], name='analytics_u_session_412ea3_idx')],
            },
        ),
    ]
