# Generated by Django 5.2.7 on 2025-10-26 23:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='volunteers.skillcategory')),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_letter', models.TextField()),
                ('why_interested', models.TextField()),
                ('relevant_experience', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('interview_scheduled', 'Interview Scheduled'), ('background_check', 'Background Check'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('interview_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('interview_location', models.CharField(blank=True, max_length=200)),
                ('interview_notes', models.TextField(blank=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerOpportunity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=500)),
                ('minimum_age', models.PositiveIntegerField(default=18)),
                ('background_check_required', models.BooleanField(default=False)),
                ('commitment_type', models.CharField(choices=[('one_time', 'One-time'), ('short_term', 'Short-term (< 3 months)'), ('long_term', 'Long-term (3+ months)'), ('ongoing', 'Ongoing')], max_length=20)),
                ('time_commitment', models.CharField(choices=[('flexible', 'Flexible'), ('part_time', 'Part-time (< 20 hours/week)'), ('full_time', 'Full-time (40+ hours/week)'), ('weekend', 'Weekends only'), ('evening', 'Evenings only')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('is_remote', models.BooleanField(default=False)),
                ('positions_available', models.PositiveIntegerField(default=1)),
                ('positions_filled', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('filled', 'Filled'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='opportunities/')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('application_count', models.PositiveIntegerField(default=0)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_opportunities', to=settings.AUTH_USER_MODEL)),
                ('preferred_skills', models.ManyToManyField(blank=True, related_name='preferred_for_opportunities', to='volunteers.skill')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='required_for_opportunities', to='volunteers.skill')),
            ],
            options={
                'verbose_name_plural': 'Volunteer Opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('hours_committed', models.PositiveIntegerField(default=0)),
                ('hours_completed', models.PositiveIntegerField(default=0)),
                ('assignment_notes', models.TextField(blank=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='volunteers.volunteerapplication')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_assignments', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_assignments', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='volunteers.volunteeropportunity')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='volunteers.volunteeropportunity'),
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('employer', models.CharField(blank=True, max_length=100)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('interests', models.TextField(blank=True)),
                ('previous_volunteer_experience', models.TextField(blank=True)),
                ('motivation', models.TextField(blank=True)),
                ('availability', models.CharField(choices=[('weekdays', 'Weekdays'), ('weekends', 'Weekends'), ('evenings', 'Evenings'), ('flexible', 'Flexible')], max_length=20)),
                ('hours_per_week', models.PositiveIntegerField(default=0)),
                ('preferred_location', models.CharField(blank=True, max_length=200)),
                ('can_travel', models.BooleanField(default=False)),
                ('has_transportation', models.BooleanField(default=False)),
                ('background_check_completed', models.BooleanField(default=False)),
                ('background_check_date', models.DateField(blank=True, null=True)),
                ('background_check_expiry', models.DateField(blank=True, null=True)),
                ('reference1_name', models.CharField(blank=True, max_length=100)),
                ('reference1_phone', models.CharField(blank=True, max_length=20)),
                ('reference1_email', models.EmailField(blank=True, max_length=254)),
                ('reference1_relationship', models.CharField(blank=True, max_length=50)),
                ('reference2_name', models.CharField(blank=True, max_length=100)),
                ('reference2_phone', models.CharField(blank=True, max_length=20)),
                ('reference2_email', models.EmailField(blank=True, max_length=254)),
                ('reference2_relationship', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('total_hours_volunteered', models.PositiveIntegerField(default=0)),
                ('skills', models.ManyToManyField(blank=True, related_name='volunteers', to='volunteers.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerTimeLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('activity_description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_time_logs', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='volunteers.volunteerassignment')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_time_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='volunteeropportunity',
            index=models.Index(fields=['status', 'start_date'], name='volunteers__status_562dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteeropportunity',
            index=models.Index(fields=['slug'], name='volunteers__slug_1f3677_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteeropportunity',
            index=models.Index(fields=['is_remote'], name='volunteers__is_remo_4d42b7_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerassignment',
            index=models.Index(fields=['status', 'start_date'], name='volunteers__status_60cdec_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerassignment',
            index=models.Index(fields=['volunteer', 'status'], name='volunteers__volunte_364603_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerapplication',
            index=models.Index(fields=['status', 'created_at'], name='volunteers__status_da595e_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerapplication',
            index=models.Index(fields=['opportunity', 'status'], name='volunteers__opportu_fafece_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='volunteerapplication',
            unique_together={('volunteer', 'opportunity')},
        ),
        migrations.AddIndex(
            model_name='volunteerprofile',
            index=models.Index(fields=['is_active'], name='volunteers__is_acti_afc88e_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerprofile',
            index=models.Index(fields=['availability'], name='volunteers__availab_90a97e_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteertimelog',
            index=models.Index(fields=['assignment', 'date'], name='volunteers__assignm_d0f5a6_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteertimelog',
            index=models.Index(fields=['volunteer', 'approved'], name='volunteers__volunte_c8560a_idx'),
        ),
    ]
