# Generated by Django 5.2.7 on 2025-10-27 00:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='additional_documents_required',
            field=models.TextField(blank=True, help_text='List any additional documents required'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='background_check_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='references_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='resume_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('documents_requested', 'Documents Requested'), ('interview_scheduled', 'Interview Scheduled'), ('background_check', 'Background Check'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('resume', 'Resume/CV'), ('cover_letter', 'Cover Letter'), ('references', 'References'), ('background_check', 'Background Check'), ('identification', 'Identification'), ('certifications', 'Certifications'), ('portfolio', 'Portfolio'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('instructions', models.TextField(help_text='Instructions for volunteers on how to complete this document')),
                ('is_required', models.BooleanField(default=True)),
                ('max_file_size', models.PositiveIntegerField(default=5242880)),
                ('allowed_file_types', models.JSONField(default=list)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='document_templates/')),
                ('expires_after_days', models.PositiveIntegerField(blank=True, help_text='Days after which document expires', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['document_type', 'is_active'], name='volunteers__documen_67cc51_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('resume', 'Resume/CV'), ('cover_letter', 'Cover Letter'), ('references', 'References'), ('background_check', 'Background Check'), ('identification', 'Identification'), ('certifications', 'Certifications'), ('portfolio', 'Portfolio'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='volunteer_documents/')),
                ('file_size', models.PositiveIntegerField()),
                ('file_type', models.CharField(max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('virus_scan_status', models.CharField(default='pending', max_length=20)),
                ('virus_scan_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='volunteers.volunteerapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_volunteer_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', 'document_type'], name='volunteers__applica_ee903c_idx'), models.Index(fields=['status', 'created_at'], name='volunteers__status_17909a_idx'), models.Index(fields=['expires_at'], name='volunteers__expires_1fe9e2_idx')],
                'unique_together': {('application', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('general', 'General Note'), ('interview', 'Interview Note'), ('reference_check', 'Reference Check'), ('background_check', 'Background Check'), ('follow_up', 'Follow-up Required'), ('concern', 'Concern/Issue')], default='general', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Internal notes are only visible to staff')),
                ('is_important', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='volunteers.volunteerapplication')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', 'note_type'], name='volunteers__applica_e002ae_idx'), models.Index(fields=['is_important', 'created_at'], name='volunteers__is_impo_4ba369_idx')],
            },
        ),
    ]
